'use strict';

// tests for currentTime
// Generated by serverless-mocha-plugin
const awsEvents = require('../awsEvents');
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('currentTime', '/handler.js', 'endpoint');

describe('currentTime', () => {
  before((done) => {
    done();
  });

  it('implement tests', async () => {
    const event = await awsEvents.sqs.receiveMessage();
    return wrapped.run(event).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
